# .github/workflows/build-cpp.yml
name: C++ Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build C++ App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Makefile
        run: make

      - name: Upload built binary (optional)
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: my_app  # adjust if your binary name differs
